singleQuote: true
semi: false
printWidth: 140
trailingComma: none

# ---- Import 정렬 플러그인 설정 추가 ----
# 플러그인 등록
plugins:
  - '@ianvs/prettier-plugin-sort-imports'

# Import 정렬 순서 정의 (위에서부터 아래 순서로 정렬됨)
importOrder:
  - '^react' # 'react'로 시작하는 모든 패키지
  - '<THIRD_PARTY_MODULES>' # 여기에 명시되지 않은 모든 서드파티 모듈
  - '^@/(.*)$' # 프로젝트 내부 경로 별칭 (@/components, @/pages 등)
  - '^[./]' # 상대 경로 (./, ../ 로 시작하는 모든 경로)

# import 그룹 사이에 빈 줄을 추가하여 가독성을 높입니다.
importOrderSeparation: true

# import { b, a } from 'foo' 와 같이 중괄호 내부의 순서도 알파벳순으로 정렬합니다.
importOrderSortSpecifiers: true
